In [ ]:
import numpy as np

**Title: 6CS012 Worksheet 0**


**Name: Deekshya Tiwari**

# **Exercise on Functions**

**Task 1 — Unit Conversion Program**

In [ ]:
def unit_converter():
    """
    Converts units for length, weight, and volume.

    Parameters:
    None (takes user input)

    Returns:
    float : converted value
    """

    try:
        print("Choose conversion type:")
        print("1. Length")
        print("2. Weight")
        print("3. Volume")

        choice = input("Enter choice (1/2/3): ")

        value = float(input("Enter the value to convert: "))

        if choice == "1":
            print("1. meters to feet")
            print("2. feet to meters")

            sub = input("Choose option: ")

            if sub == "1":
                result = value * 3.28084
                print("Result:", result, "ft")

            elif sub == "2":
                result = value / 3.28084
                print("Result:", result, "m")

        elif choice == "2":
            print("1. kg to pounds")
            print("2. pounds to kg")

            sub = input("Choose option: ")

            if sub == "1":
                result = value * 2.20462
                print("Result:", result, "lbs")

            elif sub == "2":
                result = value / 2.20462
                print("Result:", result, "kg")

        elif choice == "3":
            print("1. liters to gallons")
            print("2. gallons to liters")

            sub = input("Choose option: ")

            if sub == "1":
                result = value * 0.264172
                print("Result:", result, "gal")

            elif sub == "2":
                result = value / 0.264172
                print("Result:", result, "L")

        else:
            print("Invalid conversion type")

    except ValueError:
        print("Invalid input. Please enter numeric values.")

unit_converter()

Choose conversion type:
1. Length
2. Weight
3. Volume
Enter choice (1/2/3): 3
Enter the value to convert: 56
1. liters to gallons
2. gallons to liters
Choose option: 2
Result: 211.98310191844706 L


**Task 2 — Mathematical Operations on List**

In [ ]:
def calculate_sum(numbers):
    """Returns the sum of a list of numbers."""
    return sum(numbers)

def calculate_average(numbers):
    """Returns the average of a list of numbers."""
    return sum(numbers) / len(numbers)

def find_max(numbers):
    """Returns the maximum value."""
    return max(numbers)

def find_min(numbers):
    """Returns the minimum value."""
    return min(numbers)

try:
    data = input("Enter numbers separated by spaces: ")
    numbers = list(map(float, data.split()))

    print("Choose operation:")
    print("1 Sum")
    print("2 Average")
    print("3 Maximum")
    print("4 Minimum")

    choice = input("Enter choice: ")

    if choice == "1":
        print("Sum:", calculate_sum(numbers))

    elif choice == "2":
        print("Average:", calculate_average(numbers))

    elif choice == "3":
        print("Maximum:", find_max(numbers))

    elif choice == "4":
        print("Minimum:", find_min(numbers))

    else:
        print("Invalid operation")

except ValueError:
    print("Invalid input. Please enter numbers.")

Enter numbers separated by spaces: 2 4 6 8
Choose operation:
1 Sum
2 Average
3 Maximum
4 Minimum
Enter choice: 3
Maximum: 8.0


# **Exercise on List Manipulation:**

**1 Extract every other element**

In [ ]:
def extract_every_other(lst):
    """Returns every other element from the list."""
    return lst[::2]

print(extract_every_other([1,2,3,4,5,6]))

[1, 3, 5]


**2 Get sublist**

In [ ]:
def get_sublist(lst, start, end):
    """Returns sublist from start to end index inclusive."""
    return lst[start:end+1]

print(get_sublist([1,2,3,4,5,6],2,4))

[3, 4, 5]


**3 Reverse list**

In [ ]:
def reverse_list(lst):
    """Returns reversed list using slicing."""
    return lst[::-1]

print(reverse_list([1,2,3,4,5]))

[5, 4, 3, 2, 1]


**4 Remove first and last**

In [ ]:
def remove_first_last(lst):
    """Removes first and last element."""
    return lst[1:-1]

print(remove_first_last([1,2,3,4,5]))

[2, 3, 4]


**5 Get first n**

In [ ]:
def get_first_n(lst, n):
    """Returns first n elements."""
    return lst[:n]

print(get_first_n([1,2,3,4,5],3))

[1, 2, 3]


**6 Get last n**

In [ ]:
def get_last_n(lst, n):
    """Returns last n elements."""
    return lst[-n:]

print(get_last_n([1,2,3,4,5],2))

[4, 5]


**7 Reverse skip**

In [ ]:
def reverse_skip(lst):
    """Returns every second element from second last in reverse."""
    return lst[-2::-2]

print(reverse_skip([1,2,3,4,5,6]))

[5, 3, 1]


# **Exercise on Nested List:**

**1 Flatten list**

In [ ]:
def flatten(lst):
    """Flattens one level nested list."""
    result = []
    for sub in lst:
        result.extend(sub)
    return result

print(flatten([[1,2],[3,4],[5]]))

[1, 2, 3, 4, 5]


**2 Access nested element**

In [ ]:
def access_nested_element(lst, indices):
    """Access element using list of indices."""
    element = lst
    for i in indices:
        element = element[i]
    return element

lst = [[1,2,3],[4,5,6],[7,8,9]]
print(access_nested_element(lst,[1,2]))

6


**3 Sum nested**

In [ ]:
def sum_nested(lst):
    """Returns sum of all elements in nested list."""
    total = 0
    for item in lst:
        if isinstance(item,list):
            total += sum_nested(item)
        else:
            total += item
    return total

print(sum_nested([[1,2],[3,[4,5]],6]))

21


**4 Remove element**

In [ ]:
def remove_element(lst, elem):
    """Removes element from nested list."""
    result = []
    for item in lst:
        if isinstance(item,list):
            result.append(remove_element(item,elem))
        elif item != elem:
            result.append(item)
    return result

print(remove_element([[1,2],[3,2],[4,5]],2))

[[1], [3], [4, 5]]


**5 Find max**

In [ ]:
def find_max(lst):
    """Finds maximum in nested list."""
    maximum = float('-inf')
    for item in lst:
        if isinstance(item,list):
            maximum = max(maximum, find_max(item))
        else:
            maximum = max(maximum,item)
    return maximum

print(find_max([[1,2],[3,[4,5]],6]))

6


**6 Count occurrences**

In [ ]:
def count_occurrences(lst, elem):
    """Counts occurrences in nested list."""
    count = 0
    for item in lst:
        if isinstance(item,list):
            count += count_occurrences(item,elem)
        elif item == elem:
            count += 1
    return count

print(count_occurrences([[1,2],[2,3],[2,4]],2))

3


**7 Deep flatten**

In [ ]:
def deep_flatten(lst):
    """Flattens list of any depth."""
    result = []
    for item in lst:
        if isinstance(item,list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

print(deep_flatten([[[1,2],[3,4]],[[5,6],[7,8]]]))

[1, 2, 3, 4, 5, 6, 7, 8]


**8 Nested average**

In [ ]:
def average_nested(lst):
    """Returns average of nested list."""
    flat = deep_flatten(lst)
    return sum(flat) / len(flat)

print(average_nested([[1,2],[3,4],[5,6]]))

3.5


# **To-Do – NumPy**

**Problem 1 — Array Creation**

In [ ]:
# 1. Initialize an empty array with size 2x2
arr1 = np.empty((2,2))
print("Empty array:\n", arr1)

# 2. Initialize an all one array with size 4x2
arr2 = np.ones((4,2))
print("\nOnes array:\n", arr2)

# 3. Array filled with specific value
arr3 = np.full((3,3), 7)
print("\nFull array:\n", arr3)

# 4. Zeros array like another array
arr4 = np.zeros_like(arr2)
print("\nZeros like array:\n", arr4)

# 5. Ones array like another array
arr5 = np.ones_like(arr1)
print("\nOnes like array:\n", arr5)

# 6. Convert list to numpy array
new_list = [1,2,3,4]
arr6 = np.array(new_list)
print("\nArray from list:\n", arr6)

Empty array:
 [[2.36646384e-315 0.00000000e+000]
 [6.59737730e-310 2.30535552e-315]]

Ones array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Full array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros like array:
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

Ones like array:
 [[1. 1.]
 [1. 1.]]

Array from list:
 [1 2 3 4]


**Problem 2 — Array Manipulation**

In [ ]:
# 1. Array from 10 to 49
arr = np.arange(10,50)
print("10 to 49:\n", arr)

# 2. 3x3 matrix from 0 to 8
matrix = np.arange(9).reshape(3,3)
print("\n3x3 Matrix:\n", matrix)

# 3. Identity matrix
identity = np.eye(3)
print("\nIdentity Matrix:\n", identity)

# 4. Random array of size 30 and mean
rand_arr = np.random.random(30)
print("\nRandom Array Mean:", rand_arr.mean())

# 5. 10x10 random array with min and max
rand_matrix = np.random.random((10,10))
print("\nMinimum:", rand_matrix.min())
print("Maximum:", rand_matrix.max())

# 6. Zero array size 10 and replace 5th element
zero_arr = np.zeros(10)
zero_arr[4] = 1
print("\nZero array with 5th element replaced:\n", zero_arr)

# 7. Reverse array
arr = np.array([1,2,0,0,4,0])
print("\nReversed array:\n", arr[::-1])

# 8. 2D array with border 1 and inside 0
border = np.ones((5,5))
border[1:-1,1:-1] = 0
print("\nBorder array:\n", border)

# 9. Checkerboard pattern
checker = np.zeros((8,8))
checker[1::2,::2] = 1
checker[::2,1::2] = 1
print("\nCheckerboard pattern:\n", checker)

10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Array Mean: 0.4304072730965171

Minimum: 0.005493781682178178
Maximum: 0.9815044259881722

Zero array with 5th element replaced:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Reversed array:
 [0 4 0 0 2 1]

Border array:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

Checkerboard pattern:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


**Problem 3 — Array Operations**

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

# 1 Add arrays
print("Addition:\n", x + y)

# 2 Subtract arrays
print("\nSubtraction:\n", x - y)

# 3 Multiply array by integer
print("\nMultiply by 3:\n", x * 3)

# 4 Square each element
print("\nSquare:\n", x**2)

# 5 Dot products
print("\nv dot w:", np.dot(v,w))
print("x dot v:\n", np.dot(x,v))
print("x dot y:\n", np.dot(x,y))

# 6 Concatenate
print("\nConcatenate x and y (rows):\n", np.concatenate((x,y),axis=0))

print("\nConcatenate v and w (columns):\n",
      np.concatenate((v.reshape(-1,1), w.reshape(-1,1)),axis=1))

# 7 Concatenate x and v
try:
    print(np.concatenate((x,v)))
except Exception as e:
    print("\nError:", e)
    print("Explanation: x is 2D array while v is 1D, dimensions do not match.")

Addition:
 [[ 6  8]
 [10 13]]

Subtraction:
 [[-4 -4]
 [-4 -3]]

Multiply by 3:
 [[ 3  6]
 [ 9 15]]

Square:
 [[ 1  4]
 [ 9 25]]

v dot w: 219
x dot v:
 [29 77]
x dot y:
 [[19 22]
 [50 58]]

Concatenate x and y (rows):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v and w (columns):
 [[ 9 11]
 [10 12]]

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: x is 2D array while v is 1D, dimensions do not match.


ok above, Error occurs because x is a 2D array (matrix) while v is a 1D array.
 NumPy cannot concatenate arrays with different dimensions directly.

**Problem 4 — Matrix Operations**

In [ ]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# 1 Prove A * A^-1 = I
A_inv = np.linalg.inv(A)

result = np.dot(A, A_inv)

print("A * A^-1 =\n", result)

# 2 Prove AB ≠ BA
AB = np.dot(A,B)
BA = np.dot(B,A)

print("\nAB =\n", AB)
print("\nBA =\n", BA)

# 3 Prove (AB)^T = B^T A^T

left = (AB).T
right = np.dot(B.T, A.T)

print("\n(AB)^T =\n", left)
print("\nB^T A^T =\n", right)

A * A^-1 =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB =
 [[23 13]
 [51 29]]

BA =
 [[36 44]
 [13 16]]

(AB)^T =
 [[23 51]
 [13 29]]

B^T A^T =
 [[23 51]
 [13 29]]


**Solve Linear Equation System**

Equations:2x − 3y + z = −1 ,
x − y + 2z = −3 ,
3x + y − z = 9

In [ ]:
A = np.array([
    [2,-3,1],
    [1,-1,2],
    [3,1,-1]
])

B = np.array([-1,-3,9])

# Solve using inverse
A_inv = np.linalg.inv(A)

X = np.dot(A_inv, B)

print("Solution [x y z] =", X)

Solution [x y z] = [ 2.  1. -2.]


**Using NumPy Linear Algebra Function**

In [ ]:
solution = np.linalg.solve(A,B)

print("Solution using np.linalg.solve():\n", solution)

Solution using np.linalg.solve():
 [ 2.  1. -2.]
